app: lexet
# binpath: true
# union: true
blacklisted:
  skip:
    - libgcc_s.so.1
    - libexpat.so.1
    - libgtk-3.so.0
    - libSM.so.6
    - libasound.so.2
    - libGL.so.1
    - libEGL.so.1
    # - libstdc++.so.6
ingredients:
  dist: bionic
  sources:
    - deb http://archive.ubuntu.com/ubuntu/ bionic main universe
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe
    - deb http://archive.ubuntu.com/ubuntu bionic main
    - deb http://archive.ubuntu.com/ubuntu bionic-updates main amd64
    - deb http://archive.ubuntu.com/ubuntu bionic-updates main
    - deb http://archive.ubuntu.com/ubuntu bionic-security main
    - deb http://archive.ubuntu.com/ubuntu/ bionic main restricted
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted
    - deb http://archive.ubuntu.com/ubuntu/ bionic multiverse
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse
    - deb http://security.ubuntu.com/ubuntu bionic-security main
    - deb http://security.ubuntu.com/ubuntu bionic-security main restricted
    - deb http://security.ubuntu.com/ubuntu bionic-security universe
    - deb http://security.ubuntu.com/ubuntu bionic-security multiverse
    - deb http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
  ppas:
    - ubuntu-elisp/ppa
  packages:
    # libs
    # ---------------
    # - libgbm1
    - libxcb-dri2-0
    - libxcb-dri3-0
    - libglapi-mesa
    - libxcb-present0
    - libxcb-sync1
    - libxcb-xfixes0
    - libxshmfence1
    - libegl-mesa0
    - libexpat1
    - libegl1
    - libgtk-3-0
    - build-essential
    - libsm6
    - libasound2
    - libgl1
    # tools
    # ---------------
    - python3-venv
    - python3-pip
    - python3
    - pylint3
    - php-cli
    - php-dev
    - php-zip
    - php-phar
    - php-xml
    - php-mbstring
    - emacs-snapshot
    - pylint3
    - shellcheck

  pretend:
    - libgbm1 19.0.8-0ubuntu0~18.04.2
    # - libwebkit2gtk-4.0-37 2.24.4-0ubuntu0.18.04.1
    # - libegl1 1.0.0-2ubuntu2.3
  script:
    - cwd=$(pwd)
    - [ -d ${cwd}/.home ] || mkdir --verbose ${cwd}/.home
    - [ -f ./mu.codewith.editor.png ] || wget --continue https://raw.githubusercontent.com/mu-editor/mu/master/conf/mu.codewith.editor.png
    - [ -f ./lexet.png ] || cp ./mu.codewith.editor.png ./lexet.png
    - [ -f ./composer.phar ] || wget --continue --output-document=composer.phar https://getcomposer.org/composer.phar && chmod a+x ./composer.phar
    - [ -f ./phpcs.phar ] || wget --continue --output-document=phpcs.phar https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && chmod a+x ./phpcs.phar
    - [ -f ./phpcbf.phar ] || wget --continue --output-document=phpcbf.phar https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar && chmod a+x ./phpcbf.phar


script:
  - cwd=$(pwd)
  - echo "current directory = '${cwd}'"

  - cp ../composer.phar ${cwd}/usr/bin/composer
  - cp ../phpcs.phar ${cwd}/usr/bin/phpcs
  - cp ../phpcbf.phar ${cwd}/usr/bin/phpcbf

  - ln -s ./php7.2 ${cwd}/usr/bin/php

  # - extensions_dir=$(${cwd}/usr/bin/php -i | grep extension_dir | sed 's/extension_dir//' | sed 's/=>//' | awk '{print $1}')
  - extensions_dir=/usr/lib/php/20170718
  - cat > ${cwd}/etc/php/7.2/cli/conf.d/php.ini <<EOF
  - extension_dir=\${LEXET_MOUNT_POINT}${extensions_dir}
  - extension = phar.so
  - extension = xmlwriter.so
  - extension = json.so
  - extension = tokenizer.so
  - extension = simplexml.so
  - extension = iconv.so
  - extension = mbstring.so
  - EOF


  # import sripts lib
  - source $through_point/scripts/index.sh

  # install ctags from sources
  - install_ctags --prefix "${cwd}/usr" --local-repo-cache ../ctags --local-repo ./ctags

  # # install hunspell from sources
  #- install_hunspell --exec-prefix "${cwd}/usr" --libs-prefix "${cwd}/usr" --sysconfdir "${cwd}/etc" --local-repo-cache ../hunspell --local-repo ./hunspell

  # copy lexet packages
  - cp -r ../../lexet-packages ./lexet-packages

  # copy appimage entrypoint script
  - cp ../../AppRun ./AppRun
  - chmod a+x ./AppRun

  - [ -d ${cwd}/env ] || mkdir --verbose ${cwd}/env
  - [ -d ${cwd}/init ] || mkdir --verbose ${cwd}/init

  # create scripts
  - [ -d ${cwd}/scripts ] || mkdir --verbose ${cwd}/scripts
  - cp ${cwd}/../../incremental_tags_generation.sh ${cwd}/scripts/incremental_tags_generation.sh
  - chmod a+x ${cwd}/scripts/incremental_tags_generation.sh

  # install utils
  - install_utils --root ${cwd} --home ${cwd}/../.home

  # copy libs
  - copy_libs --src /usr/lib/x86_64-linux-gnu --destination ${cwd}/usr/lib/x86_64-linux-gnu --lib libgtk-3.so.0 --lib libasound.so.2 --lib mesa/libGL.so.1
  - copy_libs --src /lib/x86_64-linux-gnu --destination ${cwd}/lib/x86_64-linux-gnu --lib libgcc_s.so.1 --lib libexpat.so.1

  # copy lexet app
  - cp -r ../../src ./lexet

  # copy configs
  - cp -r ../../config ./config

  # create emacs link
  - ln -s ./emacs-snapshot ./usr/bin/emacs

  # prepare icon
  - cp ${cwd}/../lexet.png ${cwd}/lexet.png
  - ln -rs ${cwd}/lexet.png ${cwd}/usr/share/icons/hicolor/256x256/

  # build desktop file
  - create_lexet_desktop_file --name ./lexet.desktop
  # - ln -s ./lexet.desktop ./usr/share/applications/lexet.desktop
